version: '3.8'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=reserve
      - MYSQL_ROOT_PASSWORD=mauFsd
    ports:
      - '3306:3306'
    volumes:
      - test_vol:/var/lib/mysql
      - ./db/script:/docker-entrypoint-initdb.d

volumes:
  test_vol:
    driver: local